name: CI - Build & Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar repositorio
      - uses: actions/checkout@v3

      # 2. Login en Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construir imágenes
      - name: Build API Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api:latest ./api

      - name: Build Worker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest ./worker

      # 4. Tests mínimos
      - name: Test API container
        run: |
          container_id=$(docker run -d -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/api:latest)
          sleep 4
          curl -f http://localhost:5000/ || (docker logs $container_id && exit 1)
          docker stop $container_id

      # 5. Subir imágenes a Docker Hub
      - name: Push API Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

      - name: Push Worker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

      # 6. Guardar TAR como artefactos para el CD
      - name: Save Docker images as artifacts
        run: |
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/api:latest -o api.tar
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest -o worker.tar

      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: "*.tar"
